# Generated by Django 4.1.7 on 2023-03-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=1000, null=True)),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
